---
homeassistant:
  name: Eindhoven
  latitude: !secret house_latitude
  longitude: !secret house_longitude
  elevation: !secret house_elevation
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml

logger:
  default: info
  #logs:
  # homeassistant.components.vacuum.xiaomi_miio: debug
  # homeassistant.components.webhook: debug
  # homeassistant.components.config: debug
  # homeassistant.components.config.automation: debug

#cloud:
config:
conversation:
history:
logbook:
map:
mobile_app:

light: !include devices/light.yaml
weather: !include devices/weather.yaml
sensor: !include devices/sensor.yaml
switch: !include devices/switch.yaml
camera: !include devices/camera.yaml
input_boolean: !include devices/input_boolean.yaml
#vacuum: !include devices/vacuum.yaml

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
scene: !include scenes.yaml
