---
homeassistant:
  name: Eindhoven
  latitude: 51.479751
  longitude: 5.503628
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml

logger:
  #default: info
  logs:
    homeassistant.components.webhook: debug
    homeassistant.components.config: debug
    homeassistant.components.config.automation: debug
    homeassistant.components.vacuum.xiaomi_miio: debug

#cloud:
config:
conversation:
history:

logbook:
map:

#light: !include devices/light.yaml
#sensor: !include devices/sensor.yaml
switch: !include devices/switch.yaml

vacuum:
  - platform: xiaomi_miio
    host: 192.168.2.192
    token: !secret vacuum_token

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
scene: !include scenes.yaml
