- alias: Storage Back door opened
  trigger:
    - platform: state
      entity_id: binary_sensor.shellydw2_483fda82540e_door
      to: "on"
  action:
    - service: notify.telegram_notify
      data:
        message: "Achter deur is geopend!"
- alias: Storage motion
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor
      to: "on"

  action:
    - service: notify.telegram_notify
      data:
        message: "Beweging in de berging"
