---
- alias: Afval notificatie
  trigger:
    - platform: time
      at: "20:00:00"
  condition:
    - condition: template
      value_template: "{{ not is_state('sensor.afvalwijzer_tomorrow', 'Geen') }}"
  action:
    - service: notify.telegram_notify
      data_template:
        title: "Afval"
        message: 'Het is vandaag - {{ now().strftime("%d-%m-%Y") }}. Afvaltype(n): {{ states.sensor.afvalwijzer_tomorrow.state }} wordt opgehaald op: {{ (as_timestamp(now()) + (24*3600)) | timestamp_custom("%d-%m-%Y", True) }}!'

- alias: Reset waste notification
  trigger:
    platform: state
    entity_id: input_boolean.waste_moved
    to: "on"
    for:
      hours: 12
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.waste_moved
    - service: input_boolean.turn_on
      entity_id: input_boolean.waste_reminder

- alias: Waste has been moved
  trigger:
    platform: state
    entity_id: input_boolean.waste_moved
    to: "on"
  action:
    - service: notify.telegram_notify
      data_template:
        title: "Afval"
        message: " {{ sensor.afvalwijzer_next_item }} afval is buiten gezet."
