---
- platform: switch
  name: Badkamer plafond
  entity_id: light.bathroom_ceiling_2
- platform: switch
  name: Badkamer wasbak
  entity_id: light.bedroom_left
- platform: switch
  name: Slaapkamer plafond
  entity_id: light.bedroom_right
- platform: switch
  name: Woonkamer plafond
  entity_id: light.diner_ceiling
- platform: switch
  name: Hal 1
  entity_id: light.hall_ceiling_1
- platform: switch
  name: Hal 2
  entity_id: light.hall_ceiling_2
- platform: switch
  name: Keuken plafond 2
  entity_id: light.kitchen_ceiling_1
- platform: switch
  name: Keuken plafond 1
  entity_id: light.kitchen_ceiling_2
- platform: switch
  name: Woonkamer plafond
  entity_id: light.livingroom_ceiling
- platform: switch
  name: Kantoor plafond 1
  entity_id: light.office_ceiling
- platform: switch
  name: Kantoor plafond 2
  entity_id: light.office_ceiling_2
- platform: switch
  name: Overloop plafond
  entity_id: light.passage_ceiling
- platform: switch
  name: Saroman tower
  entity_id: light.sauroman_tower
- platform: switch
  name: Washok plafond
  entity_id: light.storage_ceiling
- platform: switch
  name: Afzuigkap links
  entity_id: light.stove_left
- platform: switch
  name: Afzuigkap rechts
  entity_id: light.stove_right
- platform: switch
  name: Tv backspot
  entity_id: light.tv_light_corner
- platform: switch
  name: WC
  entity_id: light.wc
- platform: switch
  name: Tv lamp rechts
  entity_id: switch.shellyplug_s_ab97dd
