---
- platform: buienradar
  name: "Eindhoven"
  # Force 'Meetstation Eindhoven' to be used:
  latitude: 51.45
  longitude: 5.38
  monitored_conditions:
    - stationname
    - barometerfc
    - barometerfcname
    - conditioncode
    - condition
    - conditiondetailed
    - conditionexact
    - symbol
    - feeltemperature
    - humidity
    - temperature
    - groundtemperature
    - windspeed
    - windforce
    - winddirection
    - windazimuth
    - pressure
    - visibility
    - windgust
    - precipitation
    - irradiance
    - precipitation_forecast_average
    - precipitation_forecast_total
    - rainlast24hour
    - rainlasthour
- platform: dnsip
  hostname: home-assistant.io
  name: hass
  resolver: 8.8.8.8
