---
- platform: template
  switches:
    ##Downstairs
    downstairs_lights:
      value_template: "{{ states.light.office_ceiling_1.state == 'on'
        or states.light.office_ceiling_2.state == 'on'
        or states.light.storage_ceiling.state == 'on' }}"
      turn_on:
        service: light.turn_on
        data:
          entity_id:
            - light.office_ceiling_1
            - light.office_ceiling_2
            - light.storage_ceiling
            - light.hall_ceiling_1
            - light.hall_ceiling_2
      turn_off:
        service: light.turn_off
        data:
          entity_id:
            - light.office_ceiling_1
            - light.office_ceiling_2
            - light.storage_ceiling
            - light.hall_ceiling_1
            - light.hall_ceiling_2
    office_lights:
      value_template: "{{ states.light.office_ceiling_1.state == 'on'
        or states.light.office_ceiling_2.state == 'on' }}"
      turn_on:
        service: hue.hue_activate_scene
        data:
          group_name: "Office"
          scene_name: "Build.mode"
      turn_off:
        service: light.turn_off
        data:
          entity_id:
            - light.office_ceiling_2
            - light.office_ceiling_1
    hall_lights:
      value_template: "{{ states.light.hall_ceiling_1.state == 'on'
        or states.light.hall_ceiling_2.state == 'on' }}"
      turn_on:
        service: light.turn_on
        data:
          entity_id:
            - light.hall_ceiling_1
            - light.hall_ceiling_2
      turn_off:
        service: light.turn_off
        data:
          entity_id:
            - light.hall_ceiling_1
            - light.hall_ceiling_2

    ##Firstfloor
    firstfloor_lights:
      value_template: "{{ states.light.livingroom_diner.state == 'on'
        or states.light.livingroom_ceiling.state == 'on'
        or states.light.kitchen_ceiling_1.state == 'on'
        or states.light.kitchen_ceiling_2.state == 'on'
        }}"
      turn_on:
        - service: light.turn_on
          data:
            entity_id:
              - light.livingroom_diner
              - light.livingroom_sauroman
              - light.livingroom_ceiling
              - light.livingroom_tvspot
              - light.stove_left
              - light.stove_right
              - light.kitchen_ceiling_1
              - light.kitchen_ceiling_2
        - service: switch.turn_on
          data:
            entity_id:
              - switch.shellyplug_s_ab97dd
      turn_off:
        - service: light.turn_off
          data:
            entity_id:
              - light.livingroom_diner
              - light.livingroom_sauroman
              - light.livingroom_ceiling
              - light.livingroom_tvspot
              - light.stove_left
              - light.stove_right
              - light.kitchen_ceiling_1
              - light.kitchen_ceiling_2
        - service: switch.turn_off
          data:
            entity_id:
              - switch.shellyplug_s_ab97dd
    #Livingroom
    livingroom_lights:
      value_template: "{{ states.light.livingroom_ceiling.state == 'on'
        or states.light.livingroom_diner.state == 'on' }}"
      turn_on:
        service: light.turn_on
        data:
          entity_id:
            - light.livingroom_ceiling
            - light.livingroom_diner
            - light.livingroom_sauroman
            - light.livingroom_tvspot
      turn_off:
        service: light.turn_off
        data:
          entity_id:
            - light.livingroom_ceiling
            - light.livingroom_diner
            - light.livingroom_sauroman
            - light.livingroom_tvspot
    #Kitchen
    kitchen_lights:
      value_template: "{{ states.light.kitchen_ceiling_1.state == 'on'
        or states.light.stove_left.state == 'on' }}"
      turn_on:
        service: light.turn_on
        data:
          entity_id:
            - light.kitchen_ceiling_1
            - light.kitchen_ceiling_2
            - light.stove_left
            - light.stove_right
      turn_off:
        service: light.turn_off
        data:
          entity_id:
            - light.kitchen_ceiling_1
            - light.kitchen_ceiling_2
            - light.stove_left
            - light.stove_right
    #Stove
    stove_lights:
      value_template: "{{ states.light.stove_left.state == 'on'
        or states.light.stove_right.state == 'on' }}"
      turn_on:
        service: light.turn_on
        data:
          entity_id:
            - light.stove_left
            - light.stove_right
      turn_off:
        service: light.turn_off
        data:
          entity_id:
            - light.stove_left
            - light.stove_right
    ##Second floor
    secondfloor_lights:
      value_template: "{{ states.light.bedroom_ceiling.state == 'on'
        or states.light.bathroom_sink.state == 'on'
        or states.light.passage_ceiling.state == 'on' }}"
      turn_on:
        service: light.turn_on
        data:
          entity_id:
            - light.bedroom_ceiling
            - light.passage_ceiling
            - light.bathroom_ceiling
            - light.bathroom_sink
      turn_off:
        service: light.turn_off
        data:
          entity_id:
            - light.bedroom_ceiling
            - light.passage_ceiling
            - light.bathroom_ceiling
            - light.bathroom_sink
#Bedroom
#Bathroom
